name: flutter_devarchitecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

# Tested with SDK version 3.22.3

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

# TODO: https://pub.dev/packages/hive_local_storage

# firebase
  cloud_firestore: 5.5.0 #* Android iOS macOS web Windows
  firebase_core: 3.8.1 #* Android iOS macOS web Windows
  firebase_messaging: 15.1.6 #* Android iOS macOS web
  firebase_crashlytics: 4.2.0 #* Android iOS macOS
  firebase_analytics: 11.3.6 #* Android iOS macOS web
  firebase_remote_config: 5.2.0 #* Android iOS macOS web
  firebase_performance: 0.10.0+11 #* Android iOS web

  material_color_utilities: 0.8.0
  http: 1.3.0

  # data
  collection: 1.18.0 #: All platforms
  intl: 0.19.0 #: All platforms
  data_table_2: 2.5.15 #: All platforms

  # state management
  flutter_bloc: 8.1.6 #: All platforms

  # localization
  flutter_localizations:
    sdk: flutter #: All platforms

  # design
  geekyants_flutter_gauges: 1.0.4 #: All platforms
  lottie: 3.1.2 #* Android iOS Linux macOS Windows
  graphic: 2.3.0 #: All platforms

  # dependency injection
  flutter_modular: 6.3.4 #: All platforms
  get_it: 8.0.0 #: All platforms
  provider: 6.1.2 #: All platforms

  # google
  google_search_place: 0.0.4 #: All platforms
  google_maps_flutter: 2.4.0 #: All platforms
  google_maps_flutter_web: 0.5.10 #: All platforms
  flutter_polyline_points: 2.1.0 #: All platforms

  # messages toast
  oktoast: 3.4.0 #: All platforms

  # database & storage
  shared_preferences: 2.2.3 #: All platforms
  sqlite3: 2.4.7 #: All platforms
  path: 1.9.0 #: All platforms
  path_provider: 2.1.4 #* Android iOS Linux macOS Windows

  # security
  jwt_decoder: 2.0.1 #: All platforms

  # utils
  internet_connection_checker_plus: 2.5.2 #: All platforms
  in_app_notification: ^1.1.2 #: All platforms
  url_launcher: 6.3.0 #: All platforms
  dart_amqp: 0.3.1 #* Android iOS Linux macOS Windows
  battery_plus: 5.0.2 #: All platforms
  device_info_plus: 9.0.2 #: All platforms
  permission_handler: 11.3.1 #* Android iOS web Windows
  logger: 2.4.0 #: All platforms
  pdf: 3.11.0 #: All platforms
  image: 4.2.0 #: All platforms
  excel: 4.0.2 #: All platforms
  csv: 6.0.0 #: All platforms
  share_plus: 10.0.2 #: All platforms
  local_auth: 2.2.0 #* Android iOS macOS Windows
  qr_code_scanner: 1.0.1 #* Android iOS
  universal_html: 2.2.4 #* Android iOS Linux macOS Windows
  file_picker: 8.1.7 #: All platforms
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/403.json
    - assets/404.json
    - assets/loading.json
    - assets/success.json
    - assets/error.json
    - assets/checking.json
    - assets/sending.json
    - assets/feedback.json
  fonts:
    - family: nunito
      fonts:
        - asset: assets/fonts/nunito.ttf
        - asset: assets/fonts/nunito-italic.ttf
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf