// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataAccess.Migrations.Pg
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Core.Entities.Concrete.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Core.Entities.Concrete.GroupClaim", b =>
                {
                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.HasKey("GroupId", "ClaimId");

                    b.ToTable("GroupClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "tr-TR",
                            Name = "Türkçe"
                        },
                        new
                        {
                            Id = 2,
                            Code = "en-US",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Exception")
                        .HasColumnType("text");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Core.Entities.Concrete.OperationClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Alias")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("OperationClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.Translate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LangId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Translates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "LOGIN",
                            LangId = 1,
                            Value = "Giriş TR"
                        },
                        new
                        {
                            Id = 2,
                            Code = "email",
                            LangId = 1,
                            Value = "E posta"
                        },
                        new
                        {
                            Id = 3,
                            Code = "password",
                            LangId = 1,
                            Value = "Şifre"
                        },
                        new
                        {
                            Id = 4,
                            Code = "update",
                            LangId = 1,
                            Value = "Güncelle"
                        },
                        new
                        {
                            Id = 5,
                            Code = "delete",
                            LangId = 1,
                            Value = "Sil"
                        },
                        new
                        {
                            Id = 6,
                            Code = "users_Groups",
                            LangId = 1,
                            Value = "Kullanıcının Grupları"
                        },
                        new
                        {
                            Id = 7,
                            Code = "users_claims",
                            LangId = 1,
                            Value = "Kullanıcının Yetkileri"
                        },
                        new
                        {
                            Id = 8,
                            Code = "create",
                            LangId = 1,
                            Value = "Yeni"
                        },
                        new
                        {
                            Id = 9,
                            Code = "Users",
                            LangId = 1,
                            Value = "Kullanıcılar"
                        },
                        new
                        {
                            Id = 10,
                            Code = "Groups",
                            LangId = 1,
                            Value = "Gruplar"
                        },
                        new
                        {
                            Id = 11,
                            Code = "LOGIN",
                            LangId = 2,
                            Value = "Login EN"
                        },
                        new
                        {
                            Id = 12,
                            Code = "email",
                            LangId = 2,
                            Value = "Email"
                        },
                        new
                        {
                            Id = 13,
                            Code = "password",
                            LangId = 2,
                            Value = "Password"
                        },
                        new
                        {
                            Id = 14,
                            Code = "update",
                            LangId = 2,
                            Value = "Update"
                        },
                        new
                        {
                            Id = 15,
                            Code = "delete",
                            LangId = 2,
                            Value = "Delete"
                        },
                        new
                        {
                            Id = 16,
                            Code = "users_Groups",
                            LangId = 2,
                            Value = "User's Groups"
                        },
                        new
                        {
                            Id = 17,
                            Code = "users_claims",
                            LangId = 2,
                            Value = "User's Claims"
                        },
                        new
                        {
                            Id = 18,
                            Code = "create",
                            LangId = 2,
                            Value = "Create"
                        },
                        new
                        {
                            Id = 19,
                            Code = "Users",
                            LangId = 2,
                            Value = "Users"
                        },
                        new
                        {
                            Id = 20,
                            Code = "Groups",
                            LangId = 2,
                            Value = "Groups"
                        },
                        new
                        {
                            Id = 21,
                            Code = "Operation Claim",
                            LangId = 1,
                            Value = "Operasyon Yetkileri"
                        },
                        new
                        {
                            Id = 22,
                            Code = "Operation Claim",
                            LangId = 2,
                            Value = "Operation Claim"
                        },
                        new
                        {
                            Id = 23,
                            Code = "Languages",
                            LangId = 1,
                            Value = "Diller"
                        },
                        new
                        {
                            Id = 24,
                            Code = "Languages",
                            LangId = 2,
                            Value = "Languages"
                        },
                        new
                        {
                            Id = 25,
                            Code = "Translate Words",
                            LangId = 1,
                            Value = "Dil Çevirileri"
                        },
                        new
                        {
                            Id = 26,
                            Code = "Translate Words",
                            LangId = 2,
                            Value = "Translate Words"
                        });
                });

            modelBuilder.Entity("Core.Entities.Concrete.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CitizenId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<string>("MobilePhones")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("bytea");

                    b.Property<DateTime>("RecordDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdateContactDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId");

                    b.HasIndex("CitizenId");

                    b.HasIndex("MobilePhones");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserClaim", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("ClaimId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "ClaimId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Core.Entities.Concrete.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GroupId");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Core.Entities.MobileLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("integer");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsSend")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<int>("Provider")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExternalUserId", "Provider");

                    b.ToTable("MobileLogins");
                });
#pragma warning restore 612, 618
        }
    }
}
